### ISSUE TITLE
Types for typescript support

### ISSUE THREAD

**Issue by auderer** [googleapis/nodejs-cloud-container#214]
Currently, importing this library into a typescript project gives an error:
```
Could not find a declaration file for module '@google-cloud/container'. 'node_modules/@google-cloud/container/src/index.js' implicitly has an 'any' type.
  Try `npm install @types/google-cloud__container` if it exists or add a new declaration (.d.ts) file containing `declare module '@google-cloud/container';
```

The current workaround is basically just to add `//@ts-ignore` to the line before `import`.

It would be great instead to have type definitions for this project, as the other Google client libraries for nodejs have.

**Comment by bcoe** [comment]
@auderer 👋 we're hoping in the future to move more of our libraries towards using TypeScript, at which point we will make an effort to introduce types.

**Comment by bcoe** [comment]
We've now converted the library to TypeScript :tada: let us know if you have any issues with it.
