### ISSUE TITLE
docs: add docs for key credentials

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [googleapis/nodejs-cloud-container#292]
I do have a support agreement, however for the general public it would be nice to document how to perform none-environmental authentication for the client. That is a scenario I often encounter in locked down GKE containers.

I understand that under the hood it uses gax and google-auth-library, however I am not quite sure how to set credentials from json. Following down Gax kind of lead to an abrupt end and also following other google libraries tickets / gists / docs did now work out for me.

Kind regards

**Comment by bcoe** [comment]
Thanks for the feature request @eljefedelrodeodeljefe 👌, I think you should be able to pass the credentials to the client, via a `credentials` field:

```
new Compute({
  credentials:  {client_email: 'bogus', private_key: 'bogus'}
})
```

I think we could do a better job of documenting this.

**Comment by kriston13** [comment]
Is this related to 213?
I really want to know how to authenticate to my GKE cluster & perform actions in it using a service account entirely through nodejs & the service account credentials...

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
