### ISSUE TITLE
How to call a cluster API using @google-cloud/container?

### ISSUE THREAD

**Issue by gajus** [googleapis/nodejs-cloud-container#35]
It is unclear having read the documentation how to make a Kubernetes API call using @google-cloud/container, e.g. How do I list pods in the default namespace?

Does @google-cloud/container provide an abstraction for interacting with the Kubernetes API at all?

**Comment by mhobotpplnet** [comment]
Following this as I have similar question.

**Comment by gajus** [comment]
My current understanding is that `@google-cloud/container` does not provide such functionality.

I ended up using https://github.com/godaddy/kubernetes-client.

**Comment by mhobotpplnet** [comment]
Thats for k8 client it self but I need to set something like cluster etc, and looking at the api with few changes the cloud container might be able to spit out info..

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
