### ISSUE TITLE
Listing all clusters requires too many API requests.

### ISSUE THREAD

**Issue by soudaburger** [googleapis/nodejs-cloud-container#85]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-cloud-container/issues
  - Search the issues on our "catch-all" repository: https://github.com/GoogleCloudPlatform/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS: OSX
  - Node.js version: 10.10.0
  - npm version: 6.4.1
  - `@google-cloud/container` version: 0.2.0

#### Steps to reproduce

The documentation in the README shows that you can get the list of clusters by specifying project AND zone.  Is there a better way to get ALL clusters across my organization?  Currently, having to specify the zone, results in thousands of API calls, i.e., 52 compute zones x N projects.  This seems horribly inefficient.

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by bcoe** [comment]
@soudaburger :wave: `@google-cloud/container` is a fairly thin wrapper on top of an upstream API; _the client is generated nightly, and we pull in whatever the API surface happens to me.

As of right now the `project` is a required field, and I don't believe there is a way to list clusters across all projects.

If this is a major nuisance for you, I suggest opening up an issue here, explaining your use case:

https://issuetracker.google.com/savedsearches/559746

This issue tracker is triaged by the folks who work on the API itself.
